import { app, BrowserWindow, ipcMain, IpcMainInvokeEvent } from 'electron';
import FileHandler from './collections/main/FileHandler'; 
import type FileData from "./shared/fileData";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

type IpcHandler = (
  event: IpcMainInvokeEvent,
  ...args: any[]
) => Promise<any> | any;

class App {
    //Themes
    private readonly title = 'Zector Editor';
    private readonly icon = 'build/icons/win/icon.ico';
    private readonly backgroundColor = '#ffffff';
    private readonly titleBarStyle = 'hidden';
    private readonly overlayColour = '#1b1b1b';
    private readonly symbolColour = '#ffffffff';
    private readonly titleBarHeight = 35;
    //Dimensions
    private readonly defaultHeight = 600;
    private readonly defaultWidth = 800;
    private readonly minHeight = 600;
    private readonly minWidth = 800;
    //IPC
    private readonly handlerMap: Record<string, IpcHandler> = {
        'create-new-file': () => 
            FileHandler.createFileDialog({ path: null, content: '' }),
        'new-window': () => this.createWindow(),
        'open-file': FileHandler.openFileMenu,
        'save-file': (_e, fileData: FileData) => 
            FileHandler.saveFile(fileData),
        'save-file-as': (_e, fileData: FileData) => 
            FileHandler.createFileDialog(fileData),
        'exit-window': this.closeWindow
    };

    public init(): void {
        this.setAppListeners();
        this.setIPCHandlers();
    }

    setAppListeners(): void {
        app.on('ready', this.createWindow);
        app.on('window-all-closed', this.quitApp);
        app.on('activate', this.reopenApp);
    }

    createWindow = (): void => {
        const mainWindow = new BrowserWindow({
            height: this.defaultHeight,
            width: this.defaultWidth,
            minHeight: this.minHeight,
            minWidth: this.minWidth,
            webPreferences: {
                preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
                contextIsolation: true,
                nodeIntegration: false,
            },
            title: this.title,
            icon: this.icon,
            backgroundColor: this.backgroundColor,
            titleBarStyle: this.titleBarStyle,
            ...(process.platform !== 'darwin' 
                ? { 
                    titleBarOverlay: {
                    color: this.overlayColour,
                    symbolColor: this.symbolColour,
                    height: this.titleBarHeight
                    }
                } 
                : {})
        });

        
        mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
        
        mainWindow.webContents.openDevTools();
    }

    // Quit when all windows are closed, except on macOS. There, it's common
    // for applications and their menu bar to stay active until the user quits
    // explicitly with Cmd + Q.
    quitApp(): void {
        if (process.platform !== 'darwin') {
            app.quit();
        }
    }

    reopenApp = (): void => {
        // On OS X it's common to re-create a window in the app when the
        // dock icon is clicked and there are no other windows open.
        if (BrowserWindow.getAllWindows().length === 0) {
            this.createWindow();
        }
    }

    closeWindow(): void {
        const currentWindow = BrowserWindow.getFocusedWindow();
        if (currentWindow) currentWindow.close();
    }

    setIPCHandlers(): void {
        const mapEntries = Object.entries(this.handlerMap);
        for (const [channel, handler] of mapEntries) {
            ipcMain.handle(channel, handler);
        }
    }

}

const newApp = new App();
newApp.init();