import { app, BrowserWindow, ipcMain } from 'electron';
import FileHandler from './collections/main/FileHandler'; 
import FileData from "./types/fileData";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    minHeight: 600,
    minWidth: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    title: "Kabuto Editor",
    icon: "build/icons/win/icon.ico",
    backgroundColor: "#ffffff",
    titleBarStyle: "hidden",
    ...(process.platform !== 'darwin' 
      ? { 
          titleBarOverlay: {
            color: '#1b1b1b',
            symbolColor: '#ffffffff',
            height: 35
          }
        } 
      : {})
  });

  
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.on('save-file-data', (e, fileData: FileData) => {
  if (!fileData.path || !FileHandler.verifyFile(fileData)) return FileHandler.createFileMenu(fileData);
  FileHandler.saveFileData(fileData);
});

ipcMain.on('save-file-as-data', (e, fileData: FileData) => {
  FileHandler.createFileMenu(fileData);
});